[default]

# Server
ROUTERS = [
    "alexis.auth.views:router",
    "alexis.chat.views:router",
]
CHAINS = [
    ["alexis", "alexis.chains.main:chain"]
]

# Logging
LOG_LEVEL = "INFO"
LOG_SHOW_TIME = false
LOG_HANDLER_CLASS = "rich.logging.RichHandler"

[dev]

[test]

[prod]