[default]

# Server
ROUTERS = [
    "alexis.auth.views:router",
    "alexis.chat.views:router",
]

MIDDLEWARES = [
    "alexis.components.database:SessionMiddleware",
]

# CORS
CORS_ALLOWED_ORIGINS = ["*"]

# Logging
LOG_HANDLER_CLASS = "rich.logging.RichHandler"

[development]
LOG_LEVEL = "DEBUG"
LOG_SHOW_TIME = true

[testing]
LOG_LEVEL = "DEBUG"
LOG_SHOW_TIME = true

[production]
LOG_LEVEL = "INFO"
LOG_SHOW_TIME = false
