[default]
LANGCHAIN_TRACING_V2 = true
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"


# Server
ROUTERS = [
    "alexis.auth.views:router",
    "alexis.chat.views:router",
    "alexis.chat.views:project"
]

MIDDLEWARES = [
    "alexis.components.database:SessionMiddleware",
]

LANGCHAIN_VERBOSE = true

# CORS
CORS_ALLOWED_ORIGINS = ["*"]

# Logging
LOG_HANDLER_CLASS = "rich.logging.RichHandler"

[development]
LOG_LEVEL = "INFO"
LOG_SHOW_TIME = false

[testing]
LOG_LEVEL = "DEBUG"
LOG_SHOW_TIME = false

[production]
LOG_LEVEL = "INFO"
LOG_SHOW_TIME = false
