[default]
DEBUG = true
LANGCHAIN_TRACING_V2 = true
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"


# Server
ROUTERS = [
    "alexis.auth.views:router",
    "alexis.chat.views:router",
    "alexis.chat.views:project"
]


DEFAULT_STORAGE = "alexis.components.storage:MongoStorage"


SENTRY_INTEGRATIONS = [
    "fastapi",
    "mongodb",
    "logging",
    "redis",
]
SENTRY_IGNORED_LOGGERS = []
SENTRY_ENABLE_TRACING = true
SENTRY_PROFILES_SAMPLE_RATE = 1.0
SENTRY_TRACES_SAMPLE_RATE = 1.0
SENTRY_DEBUG = false
SENTRY_ATTACH_STACKTRACE = true
SENTRY_INCLUDE_SOURCE_CONTEXT = true
SENTRY_INCLUDE_LOCAL_VARIABLES = true
SENTRY_MAX_BREADCRUMBS = 100
SENTRY_SEND_DEFAULT_PII = true


LANGCHAIN_VERBOSE = true

# CORS
CORS_ALLOWED_ORIGINS = ["*"]

# LIFESPAN FUNCTIONS
LIFESPAN_HANDLERS = [
    "alexis.components.database:lifespan",
]

# Database
MONGO_DATABASE = "alexis"

# Logging
LOG_HANDLER_CLASS = "rich.logging.RichHandler"
LOG_SHOW_TIME = false
LOG_RICH_TRACEBACKS = false
LOG_TRACEBACKS_SHOW_LOCALS = false
LOG_HANDLERS = ["console", "file"]


[development]
LOG_LEVEL = "DEBUG"
LOG_SHOW_TIME = false


[testing]
LOG_LEVEL = "DEBUG"
LOG_SHOW_TIME = false

[production]
DEBUG = false
LOG_LEVEL = "INFO"
LOG_SHOW_TIME = false
LOG_HANDLERS = ["console"]